const temperatureData = [
  { value: 32, unit: 'F' }, { value: 25, unit: 'C' }, 
  { value: 70, unit: 'F' }, { value: 18, unit: 'C' }, 
  { value: 80, unit: 'F' }, { value: 15, unit: 'C' },
  { value: 72, unit: 'F' }, { value: 28, unit: 'C' }, 
  { value: 68, unit: 'F' }, { value: 20, unit: 'C' }, 
  { value: 75, unit: 'F' }, { value: 23, unit: 'C' },
  { value: 82, unit: 'F' }, { value: 30, unit: 'C' }, 
  { value: 65, unit: 'F' }, { value: 22, unit: 'C' }, 
  { value: 77, unit: 'F' }, { value: 26, unit: 'C' },
  { value: 78, unit: 'F' }, { value: 24, unit: 'C' }, 
  { value: 73, unit: 'F' }, { value: 21, unit: 'C' }, 
  { value: 79, unit: 'F' }, { value: 27, unit: 'C' },
  { value: 71, unit: 'F' }, { value: 19, unit: 'C' }, 
  { value: 74, unit: 'F' }, { value: 17, unit: 'C' }, 
  { value: 76, unit: 'F' }, { value: 29, unit: 'C' },
];
